language: java

dist: xenial

jdk: openjdk8

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f maven-bank-example/pom.xml clean verify -Pjacoco,mutation-testing
